apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: openstack
    unsetOnly: true
resources:
  - ../../../../base/controlplane
patches:
  - path: patch-storage.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-dns.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-metallb-ips.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-scale.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-cinder-nfs.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-nova-ovn.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
  - path: patch-services.yaml
    target:
      kind: OpenStackControlPlane
      name: openstack-control-plane
