apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subscription-manager
  namespace: openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secretstore
    kind: ClusterSecretStore
  target:
    name: subscription-manager
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: subscription-manager
