apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-registry
  namespace: openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secretstore
    kind: ClusterSecretStore
  target:
    name: redhat-registry
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: redhat-registry
