apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cinder-nfs-config
  namespace: openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secretstore
    kind: ClusterSecretStore
  target:
    name: cinder-nfs-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cinder-nfs-config
