apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: libvirt-secret
  namespace: openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secretstore
    kind: ClusterSecretStore
  target:
    name: libvirt-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: libvirt-secret
