apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nova-migration-ssh-key
  namespace: openstack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secretstore
    kind: ClusterSecretStore
  target:
    name: nova-migration-ssh-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nova-migration-ssh-key
