apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret-osp-secret.yaml
  - externalsecret-libvirt-secret.yaml
  - externalsecret-cinder-nfs-config.yaml
  - externalsecret-subscription-manager.yaml
  - externalsecret-redhat-registry.yaml
  - externalsecret-dataplane-ansible-ssh.yaml
  - externalsecret-nova-migration-ssh-key.yaml
